_________2__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:32 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO2.jani '--input:constants' 'pop=5,c0_init=2,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:87): Unable to read from file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from file '/data/covidmodel/COVID2019.pm'.
_________3__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:32 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO3.jani '--input:constants' 'pop=6,c0_init=3,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:82): Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
_________4__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:32 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO4.jani '--input:constants' 'pop=7,c0_init=4,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:82): Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
_________5__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:32 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO5.jani '--input:constants' 'pop=8,c0_init=5,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:82): Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
_________6__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:32 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO6.jani '--input:constants' 'pop=9,c0_init=6,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:82): Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
_________7__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:33 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO7.jani '--input:constants' 'pop=10,c0_init=7,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:87): Unable to read from file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from file '/data/covidmodel/COVID2019.pm'.
_________8__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:33 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO8.jani '--input:constants' 'pop=11,c0_init=8,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:82): Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
_________9__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:33 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO9.jani '--input:constants' 'pop=12,c0_init=9,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:87): Unable to read from file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from file '/data/covidmodel/COVID2019.pm'.
_________10__________
Storm-conv 1.8.1

Date: Sun Feb 18 19:29:33 2024
Command line arguments: --prism /data/covidmodel/COVID2019.pm --tojani /data/covidmodel/experiments/popos/COVID2019_POPOS_TO10.jani '--input:constants' 'pop=13,c0_init=10,c1_init=0,c2_init=0,c3_init=1,c4_init=1,c5_init=1,c6_init=0,c7_init=0,c8_init=0,c9_init=0' --prop 'P=? [(c0 >= c0_init) U (q=30)&(fr0 = c0_init)]'
Current working directory: /CAVsubmission/run_scripts/conversions

ERROR (ArgumentValidators.cpp:82): Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: IllegalArgumentValueException: Unable to read from non-existing file '/data/covidmodel/COVID2019.pm'.
